version: '3.8'
services:
  db:
    image: mongo:7.0
    container_name: cql_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dio
      - MONGO_INITDB_ROOT_PASSWORD=dio
    ports:
      - "27017:27017"
    volumes:
      - cql_data:/data/db
volumes:
  cql_data: